import 'dart:convert';
import 'package:bloc/bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:meta/meta.dart';
import 'package:wheather/model/autogenerated.dart';
import 'package:wheather/service/dio/dio_helper.dart';

part 'autogen_state.dart';

class AutogenCubit extends Cubit<AutogenState> {
  AutogenCubit() : super(AutogenInitial());

  static AutogenCubit get(Context)=>BlocProvider.of(Context);

  List<Articles> articles=[];
  late Autogenerated  autogenerated;

  void getArticles()
  {
   // print('articles');
    emit(AutogenLoadingState());
    DioHelper.getData().then((value)
    {
      var jsonData=jsonDecode(value.data);
      autogenerated=Autogenerated.fromJson(jsonData);
      for(var article in autogenerated.articles!)
        articles.add(Articles());
      emit(AutogenSuccessState());
    }).catchError((error){
      print('error from this autogenerated :'+error.toString());
      emit(AutogenErrorState());
    });
  }
}
